flags: {}
packages:
- '.'
extra-deps:
- fdo-notify-0.3.1
- happstack-lite-7.3.6
- base-orphans-0.5.4
- fraction-0.1.0.4
- hspec-2.2.3
- hspec-core-2.2.3
- hspec-discover-2.2.3
- semigroups-0.16.2.2
- text-1.2.2.1
- vector-0.11.0.0
resolver: lts-7.7
