flags: {}
packages:
- '.'
extra-deps:
- fdo-notify-0.3.1
- happstack-lite-7.3.6
- hspec-2.2.3
- hspec-core-2.2.3
- hspec-discover-2.2.3
- hspec-expectations-0.7.2
- text-1.2.2.1
- vector-0.11.0.0
- fraction-0.1.0.4
resolver: lts-7.7
